{ delib, lib, ... }:
delib.module {
  name = "constants";

  options.constants = with delib; {
    username = strOption "nano";
    userfullname = strOption "nano";
    useremail = strOption "nano@nomolabs.net";
    gitname = strOption "rft";
    sshKeys = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        lemon = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIdtSRvR7Zcto/+lbuoYDkLitMEiB05X1GDFlW51DCz3 nano@nomolabs.net";
        termius = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPhrq7r1ld3FnxeyP3w/GN3lOtqDR+Wa2LnUO01OQbJI Generated By Termius";
        mistletoe = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDb5hlXcgRK/sajT0XWYIKsSDzvXfmi6YzxsMaUpjptp nano@mistletoe";
      };
    };
  };

  myconfig.always = { cfg, ... }: {
    args.shared.constants = cfg;
  };
}
